name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Deploy to Server
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USERNAME: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
          # Load environment variables
          source ~/.profile
          source ~/.bashrc

          cd /root/scraper-test

          git pull origin main

          npm install

          pm2 restart scraper
        EOF